import Head from 'next/head';
import Navbar from './components/Navbar';
import Sidebar from './components/Sidebar';
import Feed from './components/Feed';
import RightSide from './components/RightSide';
import { Box, Stack, ThemeProvider, createTheme } from '@mui/material';
import Add from './components/Add';
import { useState } from 'react';

export default function Home() {
  const [mode, setMode] = useState('light');

  const darkTheme = createTheme({
    palette: {
      mode: mode,
    },
  });

  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <Box bgcolor={'background.default'} color={'text.primary'}>
          <Navbar />
          <Stack
            direction="row"
            spacing={2}
            my={5}
            justifyContent={'space-between'}
          >
            <Sidebar setMode={setMode} mode={mode} />
            <Feed />
            <RightSide />
          </Stack>
          <Add />
        </Box>
      </ThemeProvider>
    </>
  );
}
